languageCode = "en"
languageName = "English"
weight = 1
title = "Wei's Home"

[params]
  displayName = "En"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"

[params.author]
  name = "Wei Guo"
  email = "guow1227@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "Debugging Life One Line at a Time."
  bio = "Debugging Life One Line at a Time."
  links = [
    { github = "https://github.com/Weiguo98" },
    { linkedin = "https://www.linkedin.com/in/wei-guo-a649801b7/" },
  ]