languageCode = "en"
languageName = "English"
weight = 1
title = "Wei's Home"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[author]
  name = "Wei Guo"
  email = "guow1227@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "A powerful, lightweight theme for Hugo."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { github = "https://github.com/nunocoracao/blowfish" },
    { linkedin = "https://www.linkedin.com/in/wei-guo-7b1b3b1b/" },
  ]