baseURL = 'http://weiguo98.github.io'
languageCode = 'en-us'
title = "Mole's Home"
theme = 'PaperMod'

[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Page Title"
  weight = 1
  identifier = "my-frist-post"
  url = "/posts/my-frist-post"
  parent = "posts"
